/// This file is generated (by bin/Method_template.py). Do not modify it directly.
RiotBase_DEF_FUNC_2( set_oo, 0, true ) { Rp *res = RO_CALL( set_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( set_ob, 0, true ) { Rp *res = RO_CALL( set_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( set_bo, 0, true ) { Rp *res = RO_CALL( set_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( add_oo, 0, true ) { Rp *res = RO_CALL( add_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( add_ob, 0, true ) { Rp *res = RO_CALL( add_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( add_bo, 0, true ) { Rp *res = RO_CALL( add_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( sub_oo, 0, true ) { Rp *res = RO_CALL( sub_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( sub_ob, 0, true ) { Rp *res = RO_CALL( sub_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( sub_bo, 0, true ) { Rp *res = RO_CALL( sub_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( mul_oo, 0, true ) { Rp *res = RO_CALL( mul_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( mul_ob, 0, true ) { Rp *res = RO_CALL( mul_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( mul_bo, 0, true ) { Rp *res = RO_CALL( mul_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( div_oo, 0, true ) { Rp *res = RO_CALL( div_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( div_ob, 0, true ) { Rp *res = RO_CALL( div_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( div_bo, 0, true ) { Rp *res = RO_CALL( div_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( mod_oo, 0, true ) { Rp *res = RO_CALL( mod_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( mod_ob, 0, true ) { Rp *res = RO_CALL( mod_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( mod_bo, 0, true ) { Rp *res = RO_CALL( mod_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( add_key_oo, 0, true ) { Rp *res = RO_CALL( add_key_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( add_key_ob, 0, true ) { Rp *res = RO_CALL( add_key_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( add_key_bo, 0, true ) { Rp *res = RO_CALL( add_key_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( rem_key_oo, 0, true ) { Rp *res = RO_CALL( rem_key_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( rem_key_ob, 0, true ) { Rp *res = RO_CALL( rem_key_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( rem_key_bo, 0, true ) { Rp *res = RO_CALL( rem_key_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( push_back_oo, 0, true ) { Rp *res = RO_CALL( push_back_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( push_back_ob, 0, true ) { Rp *res = RO_CALL( push_back_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( push_back_bo, 0, true ) { Rp *res = RO_CALL( push_back_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_3( insert_ooo, 0, true ) { Rp *res = RO_CALL( insert_bbb, v0, v1, v2 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); RO_CALL( del, v2 ); return res; }
RiotBase_DEF_FUNC_3( insert_oob, 0, true ) { Rp *res = RO_CALL( insert_bbb, v0, v1, v2 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_3( insert_obo, 0, true ) { Rp *res = RO_CALL( insert_bbb, v0, v1, v2 ); RO_CALL( del, v0 ); RO_CALL( del, v2 ); return res; }
RiotBase_DEF_FUNC_3( insert_obb, 0, true ) { Rp *res = RO_CALL( insert_bbb, v0, v1, v2 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_3( insert_boo, 0, true ) { Rp *res = RO_CALL( insert_bbb, v0, v1, v2 ); RO_CALL( del, v1 ); RO_CALL( del, v2 ); return res; }
RiotBase_DEF_FUNC_3( insert_bob, 0, true ) { Rp *res = RO_CALL( insert_bbb, v0, v1, v2 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_3( insert_bbo, 0, true ) { Rp *res = RO_CALL( insert_bbb, v0, v1, v2 ); RO_CALL( del, v2 ); return res; }
RiotBase_DEF_FUNC_3( remove_ooo, 0, true ) { Rp *res = RO_CALL( remove_bbb, v0, v1, v2 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); RO_CALL( del, v2 ); return res; }
RiotBase_DEF_FUNC_3( remove_oob, 0, true ) { Rp *res = RO_CALL( remove_bbb, v0, v1, v2 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_3( remove_obo, 0, true ) { Rp *res = RO_CALL( remove_bbb, v0, v1, v2 ); RO_CALL( del, v0 ); RO_CALL( del, v2 ); return res; }
RiotBase_DEF_FUNC_3( remove_obb, 0, true ) { Rp *res = RO_CALL( remove_bbb, v0, v1, v2 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_3( remove_boo, 0, true ) { Rp *res = RO_CALL( remove_bbb, v0, v1, v2 ); RO_CALL( del, v1 ); RO_CALL( del, v2 ); return res; }
RiotBase_DEF_FUNC_3( remove_bob, 0, true ) { Rp *res = RO_CALL( remove_bbb, v0, v1, v2 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_3( remove_bbo, 0, true ) { Rp *res = RO_CALL( remove_bbb, v0, v1, v2 ); RO_CALL( del, v2 ); return res; }
RiotBase_DEF_FUNC_2( equ_oo, 0, true ) { Rp *res = RO_CALL( equ_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( equ_ob, 0, true ) { Rp *res = RO_CALL( equ_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( equ_bo, 0, true ) { Rp *res = RO_CALL( equ_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( neq_oo, 0, true ) { Rp *res = RO_CALL( neq_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( neq_ob, 0, true ) { Rp *res = RO_CALL( neq_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( neq_bo, 0, true ) { Rp *res = RO_CALL( neq_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( inf_oo, 0, true ) { Rp *res = RO_CALL( inf_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( inf_ob, 0, true ) { Rp *res = RO_CALL( inf_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( inf_bo, 0, true ) { Rp *res = RO_CALL( inf_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( sup_oo, 0, true ) { Rp *res = RO_CALL( sup_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( sup_ob, 0, true ) { Rp *res = RO_CALL( sup_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( sup_bo, 0, true ) { Rp *res = RO_CALL( sup_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( inf_eq_oo, 0, true ) { Rp *res = RO_CALL( inf_eq_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( inf_eq_ob, 0, true ) { Rp *res = RO_CALL( inf_eq_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( inf_eq_bo, 0, true ) { Rp *res = RO_CALL( inf_eq_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( sup_eq_oo, 0, true ) { Rp *res = RO_CALL( sup_eq_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( sup_eq_ob, 0, true ) { Rp *res = RO_CALL( sup_eq_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( sup_eq_bo, 0, true ) { Rp *res = RO_CALL( sup_eq_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( bor_oo, 0, true ) { Rp *res = RO_CALL( bor_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( bor_ob, 0, true ) { Rp *res = RO_CALL( bor_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( bor_bo, 0, true ) { Rp *res = RO_CALL( bor_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( select_oo, 0, true ) { Rp *res = RO_CALL( select_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( select_ob, 0, true ) { Rp *res = RO_CALL( select_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( select_bo, 0, true ) { Rp *res = RO_CALL( select_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_1( neg_o, 0, true ) { Rp *res = RO_CALL( neg_b, v0 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_1( on_change_o, 0, true, Callback *c ) { Rp *res = RO_CALL( on_change_b, v0, c ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_1( then_o, 0, true, Callback *c ) { Rp *res = RO_CALL( then_b, v0, c ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( split_oo, 0, true ) { Rp *res = RO_CALL( split_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( split_ob, 0, true ) { Rp *res = RO_CALL( split_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( split_bo, 0, true ) { Rp *res = RO_CALL( split_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( join_oo, 0, true ) { Rp *res = RO_CALL( join_bb, v0, v1 ); RO_CALL( del, v0 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_2( join_ob, 0, true ) { Rp *res = RO_CALL( join_bb, v0, v1 ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_2( join_bo, 0, true ) { Rp *res = RO_CALL( join_bb, v0, v1 ); RO_CALL( del, v1 ); return res; }
RiotBase_DEF_FUNC_1( bind_by_kn_object_id_o, 0, true, const Category *cat ) { Rp *res = RO_CALL( bind_by_kn_object_id_b, v0, cat ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_1( make_inode_if_z_o, 0, true, const Category *cat ) { Rp *res = RO_CALL( make_inode_if_z_b, v0, cat ); RO_CALL( del, v0 ); return res; }
RiotBase_DEF_FUNC_1( special_func_o, 0, true, const char *func, Rp **parm, int nb_parms ) { Rp *res = RO_CALL( special_func_b, v0, func, parm, nb_parms ); RO_CALL( del, v0 ); return res; }

 
