/// This file is generated (by bin/Method_template.py). Do not modify it directly.
virtual RF_del::TF *surdef_for( RF_del f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_copy::TF *surdef_for( RF_copy f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_write_to_stream::TF *surdef_for( RF_write_to_stream f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_write_structure::TF *surdef_for( RF_write_structure f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_write_graphviz::TF *surdef_for( RF_write_graphviz f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_category::TF *surdef_for( RF_category f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_to_std_string::TF *surdef_for( RF_to_std_string f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_to_Inode::TF *surdef_for( RF_to_Inode f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_to_SI64::TF *surdef_for( RF_to_SI64 f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_to_PI64::TF *surdef_for( RF_to_PI64 f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_to_SI32::TF *surdef_for( RF_to_SI32 f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_to_PI32::TF *surdef_for( RF_to_PI32 f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_to_SI16::TF *surdef_for( RF_to_SI16 f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_to_PI16::TF *surdef_for( RF_to_PI16 f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_to_SI8::TF *surdef_for( RF_to_SI8 f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_to_PI8::TF *surdef_for( RF_to_PI8 f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_to_Bool::TF *surdef_for( RF_to_Bool f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_to_PT::TF *surdef_for( RF_to_PT f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_dasi::TF *surdef_for( RF_dasi f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_apply_DaSi::TF *surdef_for( RF_apply_DaSi f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_set_o::TF *surdef_for( RF_self_set_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_set_b::TF *surdef_for( RF_self_set_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_set_so::TF *surdef_for( RF_set_so f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_set_so_extr::TF *surdef_for( RF_set_so_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_set_sb::TF *surdef_for( RF_set_sb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_set_sb_extr::TF *surdef_for( RF_set_sb_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_set_oo::TF *surdef_for( RF_set_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_set_ob::TF *surdef_for( RF_set_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_set_bo::TF *surdef_for( RF_set_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_set_bb::TF *surdef_for( RF_set_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_add_o::TF *surdef_for( RF_self_add_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_add_b::TF *surdef_for( RF_self_add_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_so::TF *surdef_for( RF_add_so f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_so_extr::TF *surdef_for( RF_add_so_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_sb::TF *surdef_for( RF_add_sb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_sb_extr::TF *surdef_for( RF_add_sb_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_oo::TF *surdef_for( RF_add_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_ob::TF *surdef_for( RF_add_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_bo::TF *surdef_for( RF_add_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_bb::TF *surdef_for( RF_add_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_sub_o::TF *surdef_for( RF_self_sub_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_sub_b::TF *surdef_for( RF_self_sub_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sub_so::TF *surdef_for( RF_sub_so f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sub_so_extr::TF *surdef_for( RF_sub_so_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sub_sb::TF *surdef_for( RF_sub_sb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sub_sb_extr::TF *surdef_for( RF_sub_sb_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sub_oo::TF *surdef_for( RF_sub_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sub_ob::TF *surdef_for( RF_sub_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sub_bo::TF *surdef_for( RF_sub_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sub_bb::TF *surdef_for( RF_sub_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_mul_o::TF *surdef_for( RF_self_mul_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_mul_b::TF *surdef_for( RF_self_mul_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mul_so::TF *surdef_for( RF_mul_so f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mul_so_extr::TF *surdef_for( RF_mul_so_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mul_sb::TF *surdef_for( RF_mul_sb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mul_sb_extr::TF *surdef_for( RF_mul_sb_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mul_oo::TF *surdef_for( RF_mul_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mul_ob::TF *surdef_for( RF_mul_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mul_bo::TF *surdef_for( RF_mul_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mul_bb::TF *surdef_for( RF_mul_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_div_o::TF *surdef_for( RF_self_div_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_div_b::TF *surdef_for( RF_self_div_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_div_so::TF *surdef_for( RF_div_so f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_div_so_extr::TF *surdef_for( RF_div_so_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_div_sb::TF *surdef_for( RF_div_sb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_div_sb_extr::TF *surdef_for( RF_div_sb_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_div_oo::TF *surdef_for( RF_div_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_div_ob::TF *surdef_for( RF_div_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_div_bo::TF *surdef_for( RF_div_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_div_bb::TF *surdef_for( RF_div_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_mod_o::TF *surdef_for( RF_self_mod_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_mod_b::TF *surdef_for( RF_self_mod_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mod_so::TF *surdef_for( RF_mod_so f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mod_so_extr::TF *surdef_for( RF_mod_so_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mod_sb::TF *surdef_for( RF_mod_sb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mod_sb_extr::TF *surdef_for( RF_mod_sb_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mod_oo::TF *surdef_for( RF_mod_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mod_ob::TF *surdef_for( RF_mod_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mod_bo::TF *surdef_for( RF_mod_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mod_bb::TF *surdef_for( RF_mod_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_add_key_o::TF *surdef_for( RF_self_add_key_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_add_key_b::TF *surdef_for( RF_self_add_key_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_key_so::TF *surdef_for( RF_add_key_so f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_key_so_extr::TF *surdef_for( RF_add_key_so_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_key_sb::TF *surdef_for( RF_add_key_sb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_key_sb_extr::TF *surdef_for( RF_add_key_sb_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_key_oo::TF *surdef_for( RF_add_key_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_key_ob::TF *surdef_for( RF_add_key_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_key_bo::TF *surdef_for( RF_add_key_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_key_bb::TF *surdef_for( RF_add_key_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_rem_key_o::TF *surdef_for( RF_self_rem_key_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_rem_key_b::TF *surdef_for( RF_self_rem_key_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_rem_key_so::TF *surdef_for( RF_rem_key_so f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_rem_key_so_extr::TF *surdef_for( RF_rem_key_so_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_rem_key_sb::TF *surdef_for( RF_rem_key_sb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_rem_key_sb_extr::TF *surdef_for( RF_rem_key_sb_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_rem_key_oo::TF *surdef_for( RF_rem_key_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_rem_key_ob::TF *surdef_for( RF_rem_key_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_rem_key_bo::TF *surdef_for( RF_rem_key_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_rem_key_bb::TF *surdef_for( RF_rem_key_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_push_back_o::TF *surdef_for( RF_self_push_back_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_push_back_b::TF *surdef_for( RF_self_push_back_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_push_back_so::TF *surdef_for( RF_push_back_so f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_push_back_so_extr::TF *surdef_for( RF_push_back_so_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_push_back_sb::TF *surdef_for( RF_push_back_sb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_push_back_sb_extr::TF *surdef_for( RF_push_back_sb_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_push_back_oo::TF *surdef_for( RF_push_back_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_push_back_ob::TF *surdef_for( RF_push_back_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_push_back_bo::TF *surdef_for( RF_push_back_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_push_back_bb::TF *surdef_for( RF_push_back_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_insert_oo::TF *surdef_for( RF_self_insert_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_insert_ob::TF *surdef_for( RF_self_insert_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_insert_bo::TF *surdef_for( RF_self_insert_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_insert_bb::TF *surdef_for( RF_self_insert_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_soo::TF *surdef_for( RF_insert_soo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_soo_extr::TF *surdef_for( RF_insert_soo_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_sob::TF *surdef_for( RF_insert_sob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_sob_extr::TF *surdef_for( RF_insert_sob_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_sbo::TF *surdef_for( RF_insert_sbo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_sbo_extr::TF *surdef_for( RF_insert_sbo_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_sbb::TF *surdef_for( RF_insert_sbb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_sbb_extr::TF *surdef_for( RF_insert_sbb_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_ooo::TF *surdef_for( RF_insert_ooo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_oob::TF *surdef_for( RF_insert_oob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_obo::TF *surdef_for( RF_insert_obo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_obb::TF *surdef_for( RF_insert_obb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_boo::TF *surdef_for( RF_insert_boo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_bob::TF *surdef_for( RF_insert_bob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_bbo::TF *surdef_for( RF_insert_bbo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_insert_bbb::TF *surdef_for( RF_insert_bbb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_remove_oo::TF *surdef_for( RF_self_remove_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_remove_ob::TF *surdef_for( RF_self_remove_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_remove_bo::TF *surdef_for( RF_self_remove_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_remove_bb::TF *surdef_for( RF_self_remove_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_soo::TF *surdef_for( RF_remove_soo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_soo_extr::TF *surdef_for( RF_remove_soo_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_sob::TF *surdef_for( RF_remove_sob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_sob_extr::TF *surdef_for( RF_remove_sob_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_sbo::TF *surdef_for( RF_remove_sbo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_sbo_extr::TF *surdef_for( RF_remove_sbo_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_sbb::TF *surdef_for( RF_remove_sbb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_sbb_extr::TF *surdef_for( RF_remove_sbb_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_ooo::TF *surdef_for( RF_remove_ooo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_oob::TF *surdef_for( RF_remove_oob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_obo::TF *surdef_for( RF_remove_obo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_obb::TF *surdef_for( RF_remove_obb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_boo::TF *surdef_for( RF_remove_boo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_bob::TF *surdef_for( RF_remove_bob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_bbo::TF *surdef_for( RF_remove_bbo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_remove_bbb::TF *surdef_for( RF_remove_bbb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_equ_oo::TF *surdef_for( RF_equ_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_equ_ob::TF *surdef_for( RF_equ_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_equ_bo::TF *surdef_for( RF_equ_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_equ_bb::TF *surdef_for( RF_equ_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_neq_oo::TF *surdef_for( RF_neq_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_neq_ob::TF *surdef_for( RF_neq_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_neq_bo::TF *surdef_for( RF_neq_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_neq_bb::TF *surdef_for( RF_neq_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_inf_oo::TF *surdef_for( RF_inf_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_inf_ob::TF *surdef_for( RF_inf_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_inf_bo::TF *surdef_for( RF_inf_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_inf_bb::TF *surdef_for( RF_inf_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sup_oo::TF *surdef_for( RF_sup_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sup_ob::TF *surdef_for( RF_sup_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sup_bo::TF *surdef_for( RF_sup_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sup_bb::TF *surdef_for( RF_sup_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_inf_eq_oo::TF *surdef_for( RF_inf_eq_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_inf_eq_ob::TF *surdef_for( RF_inf_eq_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_inf_eq_bo::TF *surdef_for( RF_inf_eq_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_inf_eq_bb::TF *surdef_for( RF_inf_eq_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sup_eq_oo::TF *surdef_for( RF_sup_eq_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sup_eq_ob::TF *surdef_for( RF_sup_eq_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sup_eq_bo::TF *surdef_for( RF_sup_eq_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sup_eq_bb::TF *surdef_for( RF_sup_eq_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_bor_oo::TF *surdef_for( RF_bor_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_bor_ob::TF *surdef_for( RF_bor_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_bor_bo::TF *surdef_for( RF_bor_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_bor_bb::TF *surdef_for( RF_bor_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_select_oo::TF *surdef_for( RF_select_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_select_ob::TF *surdef_for( RF_select_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_select_bo::TF *surdef_for( RF_select_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_select_bb::TF *surdef_for( RF_select_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_neg_o::TF *surdef_for( RF_neg_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_neg_b::TF *surdef_for( RF_neg_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_make_ot_wrapper::TF *surdef_for( RF_make_ot_wrapper f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_pull_ot_changes::TF *surdef_for( RF_pull_ot_changes f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_write_ot_data::TF *surdef_for( RF_write_ot_data f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_new_ot_merger::TF *surdef_for( RF_new_ot_merger f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_new_cursor::TF *surdef_for( RF_new_cursor f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_rem_cursor::TF *surdef_for( RF_rem_cursor f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_get_cursors::TF *surdef_for( RF_get_cursors f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_get_possible_rights::TF *surdef_for( RF_get_possible_rights f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_get_groups_in_acl::TF *surdef_for( RF_get_groups_in_acl f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_get_users_in_acl::TF *surdef_for( RF_get_users_in_acl f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_get_grp_rights::TF *surdef_for( RF_get_grp_rights f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_get_usr_rights::TF *surdef_for( RF_get_usr_rights f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_grp_right::TF *surdef_for( RF_add_grp_right f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_add_usr_right::TF *surdef_for( RF_add_usr_right f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_rem_grp_right::TF *surdef_for( RF_rem_grp_right f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_rem_usr_right::TF *surdef_for( RF_rem_usr_right f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_on_change::TF *surdef_for( RF_self_on_change f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_on_change_s::TF *surdef_for( RF_on_change_s f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_on_change_s_extr::TF *surdef_for( RF_on_change_s_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_on_change_o::TF *surdef_for( RF_on_change_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_on_change_b::TF *surdef_for( RF_on_change_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_then::TF *surdef_for( RF_self_then f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_then_s::TF *surdef_for( RF_then_s f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_then_s_extr::TF *surdef_for( RF_then_s_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_then_o::TF *surdef_for( RF_then_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_then_b::TF *surdef_for( RF_then_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_sig_change::TF *surdef_for( RF_sig_change f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_common_symbolic_data::TF *surdef_for( RF_common_symbolic_data f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_nb_symbolic_children::TF *surdef_for( RF_nb_symbolic_children f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_symbolic_child::TF *surdef_for( RF_symbolic_child f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_is_symbolic::TF *surdef_for( RF_is_symbolic f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_is_a_s_op::TF *surdef_for( RF_is_a_s_op f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_exec::TF *surdef_for( RF_exec f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_launch::TF *surdef_for( RF_launch f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_exec_mp::TF *surdef_for( RF_exec_mp f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_del_or_cancel_exec::TF *surdef_for( RF_del_or_cancel_exec f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_get_lazy_source_info::TF *surdef_for( RF_get_lazy_source_info f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_serialize::TF *surdef_for( RF_serialize f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_set_child::TF *surdef_for( RF_set_child f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_prox_ptr::TF *surdef_for( RF_prox_ptr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_prox_ref::TF *surdef_for( RF_prox_ref f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_prox_val::TF *surdef_for( RF_prox_val f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_mod_select::TF *surdef_for( RF_mod_select f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_get_size::TF *surdef_for( RF_get_size f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_get_size_PT::TF *surdef_for( RF_get_size_PT f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_front_b::TF *surdef_for( RF_front_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_back_b::TF *surdef_for( RF_back_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_front_list_b::TF *surdef_for( RF_front_list_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_back_list_b::TF *surdef_for( RF_back_list_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_head_b::TF *surdef_for( RF_head_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_tail_b::TF *surdef_for( RF_tail_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_slice_bbb::TF *surdef_for( RF_slice_bbb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_split_oo::TF *surdef_for( RF_split_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_split_ob::TF *surdef_for( RF_split_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_split_bo::TF *surdef_for( RF_split_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_split_bb::TF *surdef_for( RF_split_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_join_oo::TF *surdef_for( RF_join_oo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_join_ob::TF *surdef_for( RF_join_ob f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_join_bo::TF *surdef_for( RF_join_bo f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_join_bb::TF *surdef_for( RF_join_bb f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_apply::TF *surdef_for( RF_apply f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_has_item_in::TF *surdef_for( RF_has_item_in f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_equ_immediate::TF *surdef_for( RF_equ_immediate f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_inf_immediate::TF *surdef_for( RF_inf_immediate f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_bind_by_path::TF *surdef_for( RF_bind_by_path f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_bind_by_object_id::TF *surdef_for( RF_bind_by_object_id f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_bind_by_kn_object_id_o::TF *surdef_for( RF_bind_by_kn_object_id_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_bind_by_kn_object_id_b::TF *surdef_for( RF_bind_by_kn_object_id_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_make_inode_if_z::TF *surdef_for( RF_self_make_inode_if_z f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_make_inode_if_z_s::TF *surdef_for( RF_make_inode_if_z_s f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_make_inode_if_z_s_extr::TF *surdef_for( RF_make_inode_if_z_s_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_make_inode_if_z_o::TF *surdef_for( RF_make_inode_if_z_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_make_inode_if_z_b::TF *surdef_for( RF_make_inode_if_z_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_self_special_func::TF *surdef_for( RF_self_special_func f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_special_func_s::TF *surdef_for( RF_special_func_s f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_special_func_s_extr::TF *surdef_for( RF_special_func_s_extr f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_special_func_o::TF *surdef_for( RF_special_func_o f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
virtual RF_special_func_b::TF *surdef_for( RF_special_func_b f, double &pertinence ) { return _surdef_for<T>( f, pertinence ); }
